substitutions:
  name: apollo-msr-2-15bda4
  friendly_name: Apollo MSR-2 15bda4

esphome:
  compile_process_limit: 1

packages:
  msr2_ble:
    url: https://github.com/ApolloAutomation/MSR-2
    ref: main
    files:
      - Integrations/ESPHome/MSR-2_BLE.yaml
    refresh: 1min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Hotspot"

api:
  encryption:
    key: YLczV7x9fE9MBA2kZwXmk5m2MMUZXk/QYD2POkLfzbw=

ota:
  - platform: esphome