substitutions:
  device_name: "matter-ble-slzb-06mu"
  friendly_name: "Matter BLE SLZB-06MU"

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  project:
    name: SMLIGHT.Matter-BLE-SLZB-06MU
    version: "1.51"
  on_boot:
    priority: 600
    then:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

esp32:
  board: esp32dev
  flash_size: 16MB
  framework:
    type: arduino

api:

logger:

ota:
  - platform: esphome

external_components:
  - source: github://tube0013/esphome-stream-server-v2

dashboard_import:
  package_import_url: github://smlight-dev/slzb-06-fw-esphome/configs/th-bt.yaml

# Ethernet (PoE powers it, ethernet does data)
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  manual_ip:
    static_ip: 10.1.1.12
    gateway: 10.1.1.1
    subnet: 255.255.255.0

uart:
  id: uart_bus
  rx_pin: GPIO5
  tx_pin: GPIO17
  baud_rate: 460800

stream_server:
  uart_id: uart_bus
  id: streamServer
  port: 6638

mdns:
  services:
    - service: "_slzb-06"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1.0
        name: Matter BLE SLZB-06MU
        radio_type: ot_rcp
        role: thread_border_router_ble_proxy
        baud_rate: 460800
        data_flow_control: hardware

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

text_sensor:
  - platform: template
    name: "SLZB-06 Uptime"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) { dys = trunc(dur / 86400); dur = dur - (dys * 86400); }
      if (dur > 3599) { hrs = trunc(dur / 3600); dur = dur - (hrs * 3600); }
      if (dur > 59) { mnts = trunc(dur / 60); dur = dur - (mnts * 60); }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 60s

sensor:
  - platform: uptime
    id: uptime_s
    update_interval: 60s

binary_sensor:
  - platform: gpio
    name: "Physical button status"
    icon: mdi:toggle-switch
    id: gpio35btn1
    pin:
      number: GPIO35
      mode:
        input: true
      inverted: yes
    on_press:
      then:
        - switch.toggle: modeSwitchTemplate

  - platform: stream_server
    stream_server: streamServer
    name: "SLZB-06* Serial Connected"

switch:
  - platform: restart
    id: coreRestart
    name: "Core only restart"

  - platform: gpio
    pin: 33
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "Radio Restart"
    icon: mdi:toggle-switch
    id: zRST
    turn_on_action:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

  - platform: template
    name: "Full (Core+Radio) Restart"
    icon: mdi:toggle-switch
    id: fullRST
    turn_on_action:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio
      - delay: 15ms
      - switch.turn_on: coreRestart

  - platform: gpio
    pin: 32
    name: "Radio flash Mode internal"
    icon: mdi:toggle-switch
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    internal: true

  - platform: template
    name: "Radio flash Mode"
    icon: mdi:cellphone-arrow-down
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - switch.toggle: zRST

  # IMPORTANT CHANGE:
  # Default to LAN mode (OFF), not USB mode (ON)
  - platform: template
    name: "DEVICE MODE SWITCH (LAN|OFF / USB|ON)"
    restore_mode: RESTORE_DEFAULT_OFF
    id: modeSwitchTemplate
    turn_on_action:
      - switch.turn_on: gpio12LED1
      - switch.turn_on: gpio4Select
      - switch.template.publish:
          id: modeSwitchTemplate
          state: ON
    turn_off_action:
      - switch.turn_off: gpio12LED1
      - switch.turn_off: gpio4Select
      - switch.template.publish:
          id: modeSwitchTemplate
          state: OFF

  - platform: gpio
    name: "DEVICE MODE SWITCH (LAN|OFF / USB|ON)"
    restore_mode: ALWAYS_OFF
    icon: mdi:toggle-switch
    internal: true
    id: gpio4Select
    pin:
      number: GPIO4

  - platform: gpio
    name: "LED - device mode (Blue)"
    restore_mode: ALWAYS_OFF
    icon: mdi:toggle-switch
    id: gpio12LED1
    pin:
      number: GPIO12

  - platform: gpio
    name: "LED - power (Yellow)"
    restore_mode: ALWAYS_ON
    icon: mdi:toggle-switch
    id: gpio14LED2
    pin:
      number: GPIO14

script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Wait 1 seconds for Radio chip to be ready"
      - delay: 1s
      - switch.turn_off: zBSL
      - logger.log: "Update Radio chip now!"