# Import statement:
# include:
#   - path: /mnt/FineBoi/Apps/homelab/docker/radarr.yml
# services: {}

---
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    # network_mode: "container:tailscale-gw"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - "7878:7878" # Radarr
    volumes:
      - /mnt/FineBoi/Apps/Radarr/config:/config
      - /mnt/Chungus/Media/Movies:/media/Movies
      - /mnt/FineBoi/Downloads:/Downloads
      - /mnt/FineBoi/Apps/Radarr/radarr_temp:/run/radarr-temp
