# Import statement:
# include:
#   - path: /mnt/FineBoi/Apps/homelab/docker/sonarr.yml
# services: {}

---
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    # network_mode: "container:tailscale-gw"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - "8989:8989" # Sonarr
    volumes:
      - /mnt/FineBoi/Apps/Sonarr/config:/config
      - /mnt/Chungus/Media/TV:/media/TV
      - /mnt/FineBoi/Downloads:/Downloads
      - /mnt/FineBoi/Apps/Sonarr/sonarr_temp:/run/sonarr-temp
