# Import statement:
# include:
#   - path: /mnt/FineBoi/Apps/homelab/docker/tailscale.yml
# services: {}

---
services:
  tailscale-gw:
    container_name: tailscale-gw
    image: tailscale/tailscale:latest
    hostname: truenas-ts-gw
    privileged: true
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=truenas-ts-gw
      - TS_EXTRA_ARGS=--exit-node=100.96.176.46 --exit-node-allow-lan-access=true --accept-routes=true
    volumes:
      - tailscale-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    ports:
      - "7878:7878" # Radarr
      - "8989:8989" # Sonarr

volumes:
  tailscale-state:
