# Import statement:
# include:
#   - path: /mnt/FineBoi/Apps/homelab/docker/tailscale.yml
# services: {}

---
services:
  tailscale-nginx:
    image: tailscale/tailscale:latest
    hostname: truenas-ts-gw
    privileged: true
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=truenas-ts-gw
      - TS_EXTRA_ARGS=--exit-node=us-sea-wg-001.mullvad.ts.net --exit-node-allow-lan-access=true
    volumes:
      - tailscale-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

volumes:
  tailscale-state:
