substitutions:
  name: apollo-msr-2-15bda4-15bda4
  friendly_name: Apollo MSR-2 15bda4
packages:
  ApolloAutomation.MSR-2_BLE: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2_BLE.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  compile_process_limit: 1
api:
  encryption:
    key: xnPHJOPT5PlwHx61guwTcySP5R9aEC28QpZpiVKFDPo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
