version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: "REPLACE_WITH_MQTT_PASSWORD"
serial:
  port: tcp://10.1.1.141:6638
  adapter: ember
  baudrate: 115200
  rtscts: false
advanced:
  log_level: info
  channel: 11
  network_key:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  pan_id: 0
  ext_pan_id:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  "0x00158d0008074ce4":
    friendly_name: Bedroom Left Window
    homeassistant:
      name: Bedroom Left Window
  "0x00158d00080680aa":
    friendly_name: Bedroom Right Window
  "0x00158d0009ee25e0":
    friendly_name: Bedroom Closet Door

